import assert from 'node:assert/strict';
import { activityCardScale, groupNearbyActivities } from '../components/map/utils/spatialActivityGroups';
const point = (id: string, lat: number, lng = 31.1) => ({ id, lat, lng });
const project = (p: ReturnType<typeof point>) => ({ x: p.lng*100000, y: p.lat*100000 });
const distant = Array.from({length:75}, (_,i) => point(String(i), 29.95+i*0.002));
assert.equal(groupNearbyActivities(distant, project, 58).length, 75, 'No city-wide remainder cluster or three-card limit');
const local = [point('a',29.96), point('b',29.9601), point('c',29.98)];
assert.deepEqual(groupNearbyActivities(local,project,58).map(g=>g.length),[2,1]);
assert.equal(groupNearbyActivities(distant,()=>({x:0,y:0}),58).length,75, 'Zooming out must not combine distant locations');
const chain = [point('a',29.96),point('b',29.9605),point('c',29.961)];
assert.deepEqual(groupNearbyActivities(chain,project,58).map(g=>g.length),[2,1], 'No transitive city-wide chains');
assert.deepEqual(groupNearbyActivities([...local].reverse(),project,58),groupNearbyActivities(local,project,58), 'Stable during panning and ranking changes');
assert.equal(groupNearbyActivities([point('a',29.96),point('b',29.96)],project,58)[0].length,2);
assert.deepEqual(groupNearbyActivities([],project,58),[]);
assert.equal(activityCardScale(10),0.78);
assert.equal(activityCardScale(20),1);
assert.ok(activityCardScale(16)>activityCardScale(14));
assert.equal(new Set(groupNearbyActivities(distant,project,58).flat().map(p=>p.id)).size,75);
console.log('PASS: spatial grouping, conservation, stability, proximity and card scaling');
