import React,{useState} from 'react';
import { CheckCircle2, AlertCircle, Phone, Navigation, Share2, MessageCircle } from 'lucide-react';
import type { ActionKind, DirectoryPlace } from '../contracts/directory';
import { Dialog } from '../design-system/Dialog';
const labels:Record<ActionKind,string>={call:'الاتصال بالنشاط',whatsapp:'التواصل عبر واتساب',directions:'الاتجاهات إلى المكان',share:'مشاركة النشاط',contact:'حفظ جهة الاتصال',report:'تصحيح معلومة',package:'طلب باقة أعمال'};
export function ActionPreview({kind,place,packageName,onClose,fail}:{kind:ActionKind;place?:DirectoryPlace;packageName?:string;onClose:()=>void;fail:boolean}) {
  const [status,setStatus]=useState<'ready'|'success'|'error'>('ready');const [message,setMessage]=useState('');const [invalid,setInvalid]=useState(false);
  const finish=()=>{if(kind==='report'&&!message.trim()){setInvalid(true);return;}setStatus(fail?'error':'success');};
  const Icon=kind==='call'?Phone:kind==='directions'?Navigation:kind==='share'?Share2:MessageCircle;
  return <Dialog title={labels[kind]} onClose={onClose}>{status==='ready'?<><Icon size={34} className="text-emerald-800 mb-4"/><h3 className="text-xl font-bold mb-3">{packageName||place?.name||'معاينة الإجراء'}</h3>{kind==='call'&&<p className="text-2xl mb-4"><bdi>{place?.phone}</bdi></p>}{kind==='directions'&&<p className="mb-4">{place?.address||'سيظهر هنا مسار الوصول إلى البوابة المختارة.'}</p>}{kind==='share'&&<p className="p-3 bg-slate-50 rounded-xl break-all mb-4" dir="ltr">directory-preview.html#/place/{place?.id}</p>}{kind==='report'&&<label className="directory-field mb-4">ما المعلومة التي تحتاج تصحيحًا؟<textarea className="border rounded-lg p-3" rows={3} maxLength={500} value={message} onChange={e=>setMessage(e.target.value)} aria-invalid={invalid} aria-describedby={invalid?'report-error':undefined}/>{invalid&&<small role="alert" id="report-error">اكتب المعلومة التي ترغب في تصحيحها.</small>}</label>}<p className="directory-form-help">هذا إجراء محاكاة فقط. لن نفتح تطبيقًا خارجيًا أو نرسل رسالة أو ننسخ بيانات أو ننشئ سجلًا.</p><button className="directory-button mt-3" onClick={finish}>تجربة نتيجة الإجراء</button></>:status==='success'?<div role="status"><CheckCircle2 size={40} className="text-emerald-700 mb-4"/><h3 className="text-xl font-bold">نجحت المحاكاة</h3><p className="my-4">اكتملت تجربة «{labels[kind]}» دون تنفيذ عملية فعلية.</p><button className="directory-button" onClick={onClose}>العودة إلى الدليل</button></div>:<div role="alert"><AlertCircle size={40} className="text-red-700 mb-4"/><h3 className="text-xl font-bold">تعذر إكمال الإجراء</h3><p className="my-4">حُفظت المعلومات داخل النافذة. يمكنك إعادة المحاولة بعد تغيير سيناريو الفشل من أدوات التجربة.</p><button className="directory-button" onClick={()=>setStatus('ready')}>العودة والمحاولة مجددًا</button></div>}</Dialog>;
}
