import React,{useState} from 'react';
import { Heart, MapPin, Star, ShieldCheck, Phone, Navigation, MessageCircle, Play } from 'lucide-react';
import type { DirectoryPlace, DirectoryActions } from '../contracts/directory';
import { CategoryIcon } from './CategoryIcon';
export interface PlaceCardProps extends DirectoryActions { place:DirectoryPlace; saved:boolean; onSave:(id:string)=>void; onOpen:(place:DirectoryPlace)=>void; }
export function PlaceCard({place:p,saved,onSave,onOpen,onAction}:PlaceCardProps) {
  const [failed,setFailed]=useState(false);
  return <article className="directory-card"><div className="directory-card-media">{p.photos[0]&&!failed?<img src={p.photos[0]} alt={`صورة توضيحية لـ ${p.name}`} width={600} height={338} loading="lazy" onError={()=>setFailed(true)}/>:<div className="directory-card-art"><CategoryIcon category={p.category}/><span>{p.category}</span></div>}<button className="directory-card-favorite" aria-pressed={saved} aria-label={`${saved?'إزالة':'حفظ'} ${p.name} ${saved?'من':'في'} المفضلة`} onClick={()=>onSave(p.id)}><Heart size={20} fill={saved?'currentColor':'none'}/></button>{p.hasVideo&&<button className="directory-card-video" onClick={()=>onOpen(p)}><Play size={15}/>جولة المكان</button>}</div><div className="directory-card-content"><div className="directory-card-meta"><span>{p.category}</span>{p.verified&&<span className="inline-flex gap-1 items-center"><ShieldCheck size={14}/>موثق</span>}</div><h3><a href={`#/place/${p.id}`} onClick={e=>{if(e.ctrlKey||e.metaKey||e.shiftKey)return;e.preventDefault();onOpen(p);}}>{p.name}</a></h3><p className="directory-card-address"><MapPin size={16}/>{p.city} · {p.area}</p><div className="directory-card-hours"><span>{p.open===null?'ساعات العمل غير متاحة':<strong style={{color:p.open?'var(--d-success)':'var(--d-muted)'}}>{p.open?'مفتوح الآن':'مغلق حاليًا'}</strong>}</span>{p.rating&&<span className="inline-flex gap-1 items-center"><Star size={14}/><bdi>{p.rating} ({p.reviewCount})</bdi></span>}</div><div className="directory-card-actions"><button onClick={()=>onAction('directions',p)} disabled={!(p.coordinates||p.mapPoint)} title={!(p.coordinates||p.mapPoint)?'الموقع الدقيق غير متاح':undefined}><Navigation size={15}/>الاتجاهات</button><button onClick={()=>onAction('whatsapp',p)} disabled={!p.phone}><MessageCircle size={15}/>واتساب</button><button onClick={()=>onAction('call',p)} disabled={!p.phone}><Phone size={15}/>اتصال</button></div></div></article>;
}

