const {chromium,setup}=require('./browser-harness.cjs');const fs=require('fs');
const out=[];let b;
async function run(s,id,fn){const p=s.page;let data;try{data=await fn();}catch(e){data={error:String(e.message).slice(0,600)};}const name=s.tag+'-'+id;await p.screenshot({path:'verification/evidence/'+name+'.png'}).catch(()=>{});fs.writeFileSync('verification/evidence/'+name+'.json',JSON.stringify({id,tag:s.tag,result:data,evidence:s.evidence},null,2));out.push({id,tag:s.tag,...data});fs.writeFileSync('verification/browser-results.json',JSON.stringify(out,null,2));console.log(name,JSON.stringify(data));}
async function goto(s,path='/search'){await s.page.goto(s.url+path);await s.page.waitForTimeout(850);}
async function open(s,name='صيدلية ألفا'){await s.page.getByText(name,{exact:true}).first().click();await s.page.waitForTimeout(350);}
async function a11y(s,trigger,label){const p=s.page;await trigger.focus();await p.keyboard.press('Enter');await p.waitForTimeout(200);const d=p.getByRole('dialog').last();const present=await d.count();if(!present)return {dialog:false};const aria=await d.getAttribute('aria-modal');const initial=await d.evaluate(e=>e.contains(document.activeElement));let escaped=false;const n=await d.locator('button,a[href],input,select,textarea,[tabindex]').count();for(let i=0;i<n+3;i++){await p.keyboard.press('Tab');if(!await d.evaluate(e=>e.contains(document.activeElement)))escaped=true;}
await d.screenshot({path:'verification/evidence/'+s.tag+'-'+label+'-open.png'});await p.keyboard.press('Escape');await p.waitForTimeout(200);return {dialog:true,ariaModal:aria,initialFocusInside:initial,tabEscaped:escaped,escapeClosed:await p.getByRole('dialog').count()===0,focusReturned:await trigger.evaluate(e=>e===document.activeElement).catch(()=>false)};}
(async()=>{b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});for(const [tag,viewport] of [['mobile',{width:390,height:844}],['desktop',{width:1280,height:900}]]){const s=await setup(b,viewport);s.tag=tag;const p=s.page;p.setDefaultTimeout(4500);
await run(s,'a-history',async()=>{await goto(s,'/search?audit=preserve');await open(s);const opened=p.url();await p.goBack();await p.waitForTimeout(250);const backClosed=await p.getByRole('dialog').count()===0;const backUrl=p.url();await p.goForward();await p.waitForTimeout(250);const forwardReopened=await p.getByRole('dialog').count()>0;await p.getByTitle('إغلاق',{exact:true}).click();await p.waitForTimeout(250);return {opened,backClosed,backUrl,forwardReopened,closeUrl:p.url(),closed:await p.getByRole('dialog').count()===0};});
await run(s,'a-direct-refresh',async()=>{await goto(s,'/biz/biz_alpha');await p.getByTitle('إغلاق',{exact:true}).click();await p.waitForTimeout(250);const before=s.calls();await p.evaluate(()=>window.dispatchEvent(new Event('directory:retry')));await p.waitForTimeout(700);return {url:p.url(),catalogRequests:s.calls()-before,remainsClosed:await p.getByRole('dialog').count()===0};});
await run(s,'b-gallery',async()=>{await goto(s);await open(s);const before=await p.getByRole('dialog').locator('img').first().getAttribute('src');await p.getByRole('dialog').getByText('صيدلية بيتا',{exact:true}).click();await p.waitForTimeout(400);const after=await p.getByRole('dialog').locator('img').first().getAttribute('src');return {before,after,staleMainPhoto:after?.includes('fixture.test/a.svg'),url:p.url()};});
await run(s,'c-filter',async()=>{await goto(s);return a11y(s,p.getByRole('button',{name:/فلترة متقدمة/}),'filter');});
await run(s,'c-video',async()=>{await goto(s);return a11y(s,p.getByRole('button',{name:/مشاهدة الفيديو التعريفي/}),'video');});
await run(s,'c-activity-photo',async()=>{await goto(s);const trigger=p.getByText('صيدلية ألفا',{exact:true}).first();const ancestor=await trigger.evaluate(e=>{let a=e;while(a&&a!==document.body){if(a.hasAttribute('tabindex')||a.tagName==='A'||a.tagName==='BUTTON')return {tag:a.tagName,role:a.getAttribute('role')};a=a.parentElement;}return null;});await open(s);const d=p.getByRole('dialog').first();let escaped=false;for(let i=0;i<35;i++){await p.keyboard.press('Tab');if(!await d.evaluate(e=>e.contains(document.activeElement)))escaped=true;}const photo=p.locator('[role="dialog"] .protected-asset-shield').first();const keyboardPhoto=await photo.evaluate(e=>({tag:e.tagName,tabindex:e.getAttribute('tabindex'),role:e.getAttribute('role')}));await photo.click();await p.waitForTimeout(100);const l=p.getByRole('dialog',{name:'معرض صور النشاط'});const opened=await l.count();let photoEscaped=false;if(opened){for(let i=0;i<8;i++){await p.keyboard.press('Tab');if(!await l.evaluate(e=>e.contains(document.activeElement)))photoEscaped=true;}await p.screenshot({path:'verification/evidence/'+s.tag+'-photo-open.png'});}await p.keyboard.press('Escape');await p.waitForTimeout(250);return {activityTriggerKeyboard:ancestor,activityTabEscaped:escaped,photoTrigger:keyboardPhoto,photoOpened:opened,photoTabEscaped:photoEscaped,dialogsAfterEscape:await p.getByRole('dialog').count(),focusAfterEscape:await p.evaluate(()=>document.activeElement?.outerHTML.slice(0,180))};});
await run(s,'d-load-error',async()=>{await s.context.clearCookies();await p.evaluate(()=>localStorage.clear());s.fail(true);await goto(s);const text=await p.locator('body').innerText();const retry=await p.getByRole('button',{name:'إعادة المحاولة',exact:true}).count();const noResults=text.includes('لم نجد أنشطة مطابقة');await p.evaluate(()=>localStorage.setItem('dalelak_user_favorites','["biz_alpha"]'));await goto(s,'/favorites');const fav=await p.locator('body').innerText();s.fail(false);await p.getByRole('button',{name:'إعادة المحاولة',exact:true}).first().click();await p.waitForTimeout(600);return {retry,noResults,favoriteErrorText:fav,favoriteRecovered:await p.getByText('صيدلية ألفا',{exact:true}).count()>0};});
await run(s,'e-two-tabs',async()=>{await goto(s);await p.evaluate(()=>localStorage.removeItem('dalelak_user_favorites'));await p.reload();await p.waitForTimeout(500);const q=await s.context.newPage();await q.goto(s.url+'/search');await q.waitForTimeout(500);await q.evaluate(()=>window.addEventListener('storage',e=>e.stopImmediatePropagation(),true));await p.getByRole('button',{name:'المفضلة',exact:true}).first().click();await p.waitForTimeout(100);await q.getByRole('button',{name:'المفضلة',exact:true}).nth(1).click();await q.waitForTimeout(150);const stored=await q.evaluate(()=>JSON.parse(localStorage.getItem('dalelak_user_favorites')));await q.close();return {stored,preservesBoth:stored.includes('biz_alpha')&&stored.includes('biz_beta'),webLocks:await p.evaluate(()=>!!navigator.locks)};});
await run(s,'f-owner',async()=>{await goto(s,'/for-business');await p.getByLabel('اسم النشاط',{exact:true}).fill('نشاط تجريبي');await p.getByLabel('رقم الهاتف',{exact:true}).fill('12345');await p.locator('button[type=submit]').click();const invalidRejected=await p.getByText(/يرجى إدخال رقم هاتف محمول مصري صحيح/).count()>0;await p.getByLabel('رقم الهاتف',{exact:true}).fill('01012345678');await p.reload();await p.waitForTimeout(350);const draft=await p.getByLabel('رقم الهاتف',{exact:true}).inputValue();await p.locator('button[type=submit]').click();return {invalidRejected,draft,interceptedWhatsApp:await p.evaluate(()=>window.__opened.map(u=>new URL(u).hostname)),retry:await p.getByRole('link',{name:'إعادة فتح واتساب'}).count(),edit:await p.getByRole('button',{name:'تعديل البيانات'}).count(),popupBlockedClaim:await p.getByText(/فُتحت رسالة جاهزة/).count()>0};});
await run(s,'g-leaflet',async()=>{await goto(s,'/map');await p.waitForTimeout(1500);const before=s.evidence.network.length;const text=await p.locator('body').innerText();const retry=p.getByRole('button',{name:/إعادة المحاولة/});const count=await retry.count();if(count){await retry.first().click();await p.waitForTimeout(500);}return {text,retryCount:count,newNetworkAttempts:s.evidence.network.length-before,alerts:await p.evaluate(()=>window.__alerts)};});
await run(s,'i-unknown',async()=>{await goto(s,'/route-does-not-exist');const unknown=await p.locator('body').innerText();await goto(s,'/biz/biz_missing');const missing=await p.locator('body').innerText();return {unknown,missing};});
await s.context.close();fs.appendFileSync('verification/STATE.md','\nBrowser '+tag+' main scenarios finished; raw results browser-results.json. GPS/offline and isolated dialog testing remain.\n');}
await b.close();})().catch(async e=>{console.error(e);await b?.close();process.exitCode=1;});
