const fs=require('fs'),path=require('path'),cp=require('child_process');const{chromium,setup,rows}=require('./browser-harness.cjs');
const root=path.resolve('verification/mutation-copy'),base=path.resolve('verification/baseline');const tsx=path.resolve('node_modules/tsx/dist/cli.mjs');const results=[];
function edit(p,fn){const f=path.join(root,p),old=fs.readFileSync(f,'utf8'),next=fn(old);if(next===old)throw Error('Mutation no-op '+p);fs.writeFileSync(f,next);}
const changes={
 U1:()=>edit('src/utils/directoryFiltering.ts',s=>s.replace('\n\n        }\n\n        const mainKeyword','\n          return true;\n        }\n\n        const mainKeyword')),
 U2:()=>fs.copyFileSync(path.join(base,'src/utils/directoryEnhancements.ts'),path.join(root,'src/utils/directoryEnhancements.ts')),
 U3:()=>fs.copyFileSync(path.join(base,'src/components/PublicShowcase.tsx'),path.join(root,'src/components/PublicShowcase.tsx')),
 U4:()=>fs.copyFileSync(path.join(base,'src/components/PublicShowcase.tsx'),path.join(root,'src/components/PublicShowcase.tsx')),
 U7:()=>{fs.copyFileSync(path.join(base,'src/components/activity/ActivityDetailModal.tsx'),path.join(root,'src/components/activity/ActivityDetailModal.tsx'));edit('src/components/PublicShowcase.tsx',s=>s.replace('key={selectedBiz.id}',''));},
 B1:()=>edit('src/shared/publicBusiness.ts',s=>s.replace("status==='published'","true")),
 B2:()=>edit('src/services/catalogState.ts',s=>s.replace('if(b&&isPublicBusiness(b))map.set(id,b);','if(b&&isPublicBusiness(b)){if(map.has(id))map.set(id,b);}')),
 B3:()=>edit('src/services/catalogState.ts',s=>s.replace('JSON.stringify(a)===JSON.stringify(b)','JSON.stringify(a.map(({description,...rest}:any)=>rest))===JSON.stringify(b.map(({description,...rest}:any)=>rest))')),
 B4:()=>edit('src/App.tsx',s=>s.replace('const live=new Map(overrides);','const live=new Map<string,Business|null>();'))
};
const modified=['src/utils/directoryFiltering.ts','src/utils/directoryEnhancements.ts','src/components/PublicShowcase.tsx','src/components/activity/ActivityDetailModal.tsx','src/shared/publicBusiness.ts','src/services/catalogState.ts','src/App.tsx'];
function restore(){for(const p of modified)fs.copyFileSync(p,path.join(root,p));}
function existing(){const r=cp.spawnSync(process.execPath,[tsx,path.join(root,'src/tests/repair.test.ts')],{encoding:'utf8',timeout:45000});return {exit:r.status,output:(r.stdout+r.stderr).replace(/sb_(?:publishable|secret)_[\w-]+/g,'[REDACTED]')};}
function unit(id){const r=cp.spawnSync(process.execPath,[tsx,path.resolve('verification/mutation-probe.ts')],{env:{...process.env,MUTATION_ROOT:root,MUTATION_ID:id},encoding:'utf8',timeout:15000});return {pass:r.status===0,exit:r.status,output:r.stdout+r.stderr};}
async function browserTest(b,id){const s=await setup(b,{width:390,height:844},5293),p=s.page;p.setDefaultTimeout(3500);let data;try{
 if(id==='B4')await s.context.route(u=>u.pathname==='/src/services/supabaseClient.ts',r=>r.fulfill({contentType:'application/javascript',body:`export const SUPABASE_REST_BASE='https://mock.supabase.co/rest/v1';export const SUPABASE_ANON_KEY='placeholder';export const supabase={channel(){const c={on(t,o,f){window.__realtime=f;return c;},subscribe(){return c;}};return c;},removeChannel(){}};`}));
 await p.goto(s.url+(id==='U4'?'/biz/biz_alpha':'/search'));await p.waitForTimeout(700);
 if(id==='U3'){await p.getByText('صيدلية ألفا',{exact:true}).first().click();await p.waitForTimeout(200);await p.goBack();await p.waitForTimeout(150);await p.goForward();await p.waitForTimeout(200);data={pass:await p.getByTitle('إغلاق',{exact:true}).count()>0};}
 if(id==='U4'){await p.getByTitle('إغلاق',{exact:true}).click();await p.waitForTimeout(180);rows[1].name_ar='صيدلية بيتا محدثة';await p.evaluate(()=>window.dispatchEvent(new Event('directory:retry')));await p.waitForTimeout(500);data={pass:await p.getByTitle('إغلاق',{exact:true}).count()===0};rows[1].name_ar='صيدلية بيتا';}
 if(id==='U7'){await p.getByText('صيدلية ألفا',{exact:true}).first().click();await p.waitForTimeout(250);await p.getByText('صيدلية بيتا',{exact:true}).last().click();await p.waitForTimeout(250);const src=await p.locator('div.fixed.inset-0.z-50').last().locator('img').first().getAttribute('src');data={pass:!src.includes('fixture.test/a.svg'),src};}
 if(id==='B4'){let held;await s.context.route('**/rest/v1/businesses?**',r=>{held=r;});await p.evaluate(()=>window.dispatchEvent(new Event('directory:retry')));for(let i=0;i<40&&!held;i++)await p.waitForTimeout(25);if(!held)throw Error('No held REST');await p.evaluate(row=>window.__realtime({eventType:'UPDATE',new:row,old:{id:row.id}}),{...rows[0],name_ar:'صيدلية ألفا لحظية'});await p.waitForTimeout(100);const liveBefore=await p.getByText('صيدلية ألفا لحظية',{exact:true}).count()>0;await held.fulfill({contentType:'application/json',headers:{'content-range':'0-1/2'},body:JSON.stringify(rows)});await p.waitForTimeout(300);data={pass:liveBefore&&await p.getByText('صيدلية ألفا لحظية',{exact:true}).count()>0,liveBefore};}
 await p.screenshot({path:`verification/evidence/mutation-${id}-${Date.now()}.png`});data.pageErrors=s.evidence.errors;
 }catch(e){data={pass:null,harnessError:e.message};}finally{rows[1].name_ar='صيدلية بيتا';await s.context.close();}return data;}
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});restore();const controlExisting=existing();fs.writeFileSync('verification/evidence/mutation-existing-control.txt',controlExisting.output);console.log('Existing suite control',controlExisting.exit);
for(const id of Object.keys(changes)){restore();const control=['U3','U4','U7','B4'].includes(id)?await browserTest(b,id):unit(id);changes[id]();await new Promise(r=>setTimeout(r,350));const mutant=['U3','U4','U7','B4'].includes(id)?await browserTest(b,id):unit(id);const old=existing();fs.writeFileSync(`verification/evidence/mutation-${id}-existing.txt`,old.output);results.push({id,control,mutant,existingSuitePassesWithoutFix:old.exit===0,existingExit:old.exit});fs.writeFileSync('verification/mutation-results.json',JSON.stringify({controlExistingExit:controlExisting.exit,results},null,2));fs.appendFileSync('verification/STATE.md',`\nMutation ${id} complete: stronger control=${control.pass}, mutant=${mutant.pass}, existing suite exit=${old.exit}. See mutation-results.json.\n`);console.log(id,JSON.stringify({control:control.pass,mutant:mutant.pass,existingPass:old.exit===0}));}
restore();await b.close();})();
