import assert from 'node:assert/strict';import fs from 'node:fs';import{imp,installFetchMock,mockRes,json,isSupabaseBusinesses}from'./lib/harness';import{normalizeArabicText}from'../src/utils/arabicSearch';
const results:any[]=[];const row:any={id:'biz_extra',name_ar:'EXTRA_ROW',verification_status:'verified',package_id:'pkg_basic',notes:'{}',photos:[],created_at:'2026-01-01',city:'حدائق الأهرام'};
const req={query:{biz:row.id},headers:{host:'www.dalilaak.com'},method:'GET'}as any;
async function run(id:string,fn:()=>Promise<any>){try{results.push({id,result:await fn()});}catch(e:any){results.push({id,error:e.message});}fs.writeFileSync('verification/stronger-results.json',JSON.stringify(results,null,2));console.log(id,JSON.stringify(results.at(-1)));}
await run('U1-normalization',async()=>({normalized:normalizeArabicText('حدائق الأهرام'),earlyReturnCondition:normalizeArabicText('حدائق الأهرام').includes('حدايق الاهرام'),aliasMatches:normalizeArabicText('هضبة الأهرام').includes('هضبه الاهرام')}));
await run('B7-true-server-cap-unique',async()=>{const m=await imp('api/sitemap.ts');const all=Array.from({length:73},(_,i)=>({...row,id:'biz_cap_'+i}));const ranges:string[]=[];const mock=installFetchMock([{name:'cap17',match:isSupabaseBusinesses,respond:(_u,init)=>{const range=String(init?.headers?.Range||'0-499');ranges.push(range);const from=Number(range.split('-')[0]);const data=all.slice(from,Math.min(from+17,Number(range.split('-')[1])+1));return json(data,{headers:{'content-range':`${from}-${from+data.length-1}/${all.length}`}});}}]);try{const{res,state}=mockRes();await m.default({...req,query:{}},res);const body=String(state.body);const ids=[...body.matchAll(/biz_cap_\d+/g)].map(x=>x[0]);assert.equal(state.statusCode,200);assert.deepEqual([...new Set(ids)].sort(),all.map(x=>x.id).sort());assert.equal(ids.length,73);return {pass:true,requests:ranges.length,ranges,unique:73};}finally{mock.restore();}});
await run('B1-select-projection',async()=>{const m=await imp('api/share.ts');const cases=[];for(const flags of [{is_deleted:true},{published_status:'draft'}]){let requested:string[]=[];const mock=installFetchMock([{name:'realistic-select',match:isSupabaseBusinesses,respond:u=>{requested=new URL(u).searchParams.get('select')!.split(',');const raw={...row,...flags};const projected=Object.fromEntries(requested.filter(k=>k in raw).map(k=>[k,raw[k]]));return json([projected]);}}]);try{const{res,state}=mockRes();await m.default(req,res);cases.push({flags,selectedGuardColumn:requested.includes(Object.keys(flags)[0]),status:state.statusCode,namePublished:String(state.body).includes('EXTRA_ROW')});}finally{mock.restore();}}return {cases,limitation:'Schema-dependent: DB was not inspected. If row-level guard columns exist, selecting without them defeats the guard. Original mocks returned unselected fields.'};});
await run('B10-image-body-stall',async()=>{const m=await imp('api/biz-og.ts');const photo='https://fixture.supabase.co/storage/v1/object/public/stall.jpg';let streamController:any,signal:any,photoFetched=false;const mock=installFetchMock([{name:'row',match:isSupabaseBusinesses,respond:()=>json([{...row,photos:[photo],notes:JSON.stringify({coverPhoto:photo})}])},{name:'stall',match:u=>u===photo,respond:(_u,init)=>{photoFetched=true;signal=init.signal;const body=new ReadableStream({start(c){streamController=c;c.enqueue(new Uint8Array([1]));signal?.addEventListener('abort',()=>c.error(new Error('aborted')));}});return new Response(body,{headers:{'content-type':'image/jpeg'}});}}]);try{const{res,state}=mockRes();let completed=false;const promise=m.default(req,res).then(()=>completed=true);await new Promise(r=>setTimeout(r,5700));const result={photoFetched,completedBy5700ms:completed,signalAborted:signal?.aborted,advertisedFetchTimeoutMs:5000};streamController.close();await promise;return result;}finally{mock.restore();}});
fs.appendFileSync('verification/STATE.md','\nAdditional stronger probes finished: actual server page cap/unique IDs, U1 normalization, selected-column policy gap (schema conditional), OG body stall. See stronger-results.json.\n');
