import React,{useState} from 'react';
import brandLogo from '../preview/assets/brand-logo.svg';
import { MapPin,Compass,Search,Heart,Map,Plus,Menu,X } from 'lucide-react';
export function Navigation({path,onNavigate,savedCount}:{path:string;onNavigate:(path:string)=>void;savedCount:number}) {
  const [menu,setMenu]=useState(false);
  const links=[{path:'/discover',label:'اكتشف',desktop:'اكتشف دليلك',icon:Compass},{path:'/search',label:'البحث',desktop:'الأنشطة والخدمات',icon:Search},{path:'/map',label:'الخريطة',desktop:'الخريطة',icon:Map},{path:'/favorites',label:'المفضلة',desktop:`المفضلة${savedCount?` (${savedCount})`:''}`,icon:Heart}];
  const go=(next:string)=>{setMenu(false);onNavigate(next);};
  return <><header className="directory-header" onKeyDown={e=>{if(e.key==='Escape')setMenu(false);}}><div className="directory-container directory-header-inner"><button className="directory-brand" aria-label="دليلك — الرئيسية" onClick={()=>go('/')}><img className="directory-official-logo" src={brandLogo} alt="" width={48} height={48}/><span><strong>دليلك</strong><small>كل مكان… أقرب إليك</small></span></button><nav className="directory-nav" aria-label="التنقل الرئيسي">{links.map(link=><button key={link.path} aria-current={path===link.path?'page':undefined} onClick={()=>go(link.path)}>{link.desktop}</button>)}</nav><div className="directory-header-actions"><button className="directory-header-pricing" onClick={()=>go('/pricing')}>باقات الأعمال</button><button className="directory-button gold" onClick={()=>go('/for-business')}><Plus size={17}/>أضف نشاطك</button><button className="directory-menu-toggle" aria-label="القائمة الرئيسية" aria-expanded={menu} aria-controls="preview-mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div>{menu&&<nav id="preview-mobile-menu" className="directory-mobile-menu" aria-label="روابط إضافية">{[...links,{path:'/pricing',label:'باقات الأعمال'},{path:'/about',label:'عن دليلك'}].map(link=><button key={link.path} onClick={()=>go(link.path)}>{link.label}</button>)}</nav>}</header><nav className="directory-bottom-nav" aria-label="التنقل على الهاتف">{links.map(({path:next,label,icon:Icon})=><button key={next} onClick={()=>go(next)} aria-current={path===next?'page':undefined}><Icon size={21}/><span>{label}</span></button>)}</nav></>;
}

