import React,{useState} from 'react';
import { Check, ArrowLeft, Sparkles } from 'lucide-react';
import { useDirectoryCatalog } from '../contracts/DirectoryCatalogProvider';
import { Dialog } from '../design-system/Dialog';
export function PricingScreen({onRequest,onNavigate}:{onRequest:(name:string)=>void;onNavigate:(path:string)=>void}) {
  const catalog=useDirectoryCatalog();
  const [track,setTrack]=useState('التوثيق والتأسيس'); const [details,setDetails]=useState<string|null>(null);
  const pack=catalog.packages.find(item=>item.id===details);
  return <div className="directory-container directory-section"><header className="directory-page-heading text-center"><div className="directory-kicker justify-center"><Sparkles size={18}/>مساحة أكبر لنمو نشاطك</div><h1 className="directory-heading">اختر ما يحتاجه نشاطك، بوضوح.</h1><p className="directory-description mx-auto">قارن الخدمات، اعرف المخرجات، ثم اختر الخطوة المناسبة.</p><p className="directory-form-help">الباقات والأسعار هنا بيانات محاكاة غير ملزمة، وليست عرضًا تجاريًا.</p></header><div className="flex justify-center gap-3 flex-wrap my-6" role="group" aria-label="مسارات الباقات">{['التوثيق والتأسيس','التسويق والنمو','الحلول الرقمية'].map(t=><button key={t} className="directory-chip" aria-pressed={track===t} onClick={()=>setTrack(t)}>{t}</button>)}</div><div className="directory-grid">{catalog.packages.filter(item=>item.track===track).map(item=><article key={item.id} className={`directory-package ${item.popular?'featured':''}`}><div className="directory-kicker">{item.popular?'خيار متكامل':'خدمات الأعمال'}</div><h2>{item.name}</h2><p className="text-slate-600">{item.description}</p><div><strong className="price">{item.price}</strong><p className="text-sm text-slate-600">{item.unit}</p></div><ul>{item.features.map(feature=><li key={feature}><Check size={17} className="text-emerald-700"/>{feature}</li>)}</ul><button className="directory-button" onClick={()=>onRequest(item.name)}>طلب هذه الباقة<ArrowLeft size={16}/></button><button className="directory-button secondary" onClick={()=>setDetails(item.id)}>التفاصيل ومدة التنفيذ</button></article>)}</div><section className="directory-owner-banner mt-10"><div><h2>تبحث عن إدراج نشاطك فقط؟</h2><p>ابدأ بالبيانات الأساسية، ثم تعرّف على الخدمات الإضافية.</p></div><button className="directory-button secondary" onClick={()=>onNavigate('/for-business')}>أضف نشاطك</button></section>{pack&&<Dialog title={pack.name} onClose={()=>setDetails(null)}><p>{pack.description}</p><ul className="space-y-3 my-5">{pack.features.map(item=><li key={item} className="flex gap-2"><Check size={18}/>{item}</li>)}</ul><p className="mb-5">مدة التنفيذ التوضيحية: {pack.duration}</p><p className="directory-form-help">لا دفع أو تعاقد داخل هذه المعاينة.</p><button className="directory-button" onClick={()=>onRequest(pack.name)}>معاينة طلب الباقة</button></Dialog>}</div>;
}
