import { Business } from '../../../types';

export interface SearchViewProps {
  filteredBusinesses: Business[];
  allBusinesses: Business[];
  loading: boolean;
  searchQuery: string;
  onSearchChange: (q: string) => void;
  selectedGov: string;
  onGovChange: (g: string) => void;
  selectedCity: string;
  onCityChange: (c: string) => void;
  selectedZone: string;
  onZoneChange: (z: string) => void;
  categoryFilter: string;
  onCategoryChange: (cat: string) => void;
  subcategoryFilter: string;
  onSubcategoryChange: (cat: string) => void;
  sortBy: 'default' | 'nearest' | 'newest' | 'has_video' | 'open_now' | 'alpha';
  onSortChange: (s: any) => void;
  openNowOnly: boolean;
  onToggleOpenNow: () => void;
  verifiedOnly?: boolean;
  hasRatingOnly: boolean;
  onToggleHasRating: () => void;
  hasVideoOnly: boolean;
  onToggleHasVideo: () => void;
  userCoords: { lat: number; lng: number } | null;
  isLocatingUser: boolean;
  onRequestLocation: () => void;
  onOpenBusiness: (biz: Business) => void;
  onToggleFavorite: (id: string) => void;
  favorites: string[];
  onResetAllFilters: () => void;
  hasActiveFilters: boolean;
  onOpenVideoModal?: (biz: Business) => void;
  onNavigate: (path: string) => void;
  onReshuffle?: () => void;
  directoryScope?: 'hadayek' | 'all';
  onDirectoryScopeChange?: (scope: 'hadayek' | 'all') => void;
}
